### ISSUE TITLE
Css not loading properly

### ISSUE THREAD

**Issue by Seankuwamoto** [FairfieldBW/clock#3]
# In the mobile version of the Bayclock website, the css did not load properly. Would a mobile application would better suit users looking to access Bayclock from their phones? Perchance.

![why_are_you_reading_my_file_naming_conventions](https://user-images.githubusercontent.com/56642599/219499582-9b5629fb-0637-4b8f-9c64-19084b4705ca.png)

**Comment by lucaskchang** [comment]
I heard there was someone working on an app like that, but they never got around to finishing it. What a shame

**Comment by lucaskchang** [comment]
Also wrong repo
